name: Push to Azure DevOps

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Azure DevOps remote
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://venubura123:${AZURE_DEVOPS_PAT}@dev.azure.com/venubura123/aparna/_git/demorepo
          git remote -v

      - name: Push to Azure DevOps
        run: |
          git push azure main --force
